-- AlterTable
ALTER TABLE "Splace" ALTER COLUMN "geolog" SET DATA TYPE DECIMAL(11,8),
ALTER COLUMN "geolat" SET DATA TYPE DECIMAL(11,8);

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "currentLat" SET DATA TYPE DECIMAL(11,8),
ALTER COLUMN "currentLog" SET DATA TYPE DECIMAL(11,8);
